<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVsp8yan\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVsp8yan/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVsp8yan.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVsp8yan\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVsp8yan\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Vsp8yan',
    'container.build_id' => '78255137',
    'container.build_time' => 1544308536,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerVsp8yan');
