<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0fjlygh\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0fjlygh/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container0fjlygh.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container0fjlygh\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container0fjlygh\appDevDebugProjectContainer(array(
    'container.build_hash' => '0fjlygh',
    'container.build_id' => '7f686c97',
    'container.build_time' => 1544542550,
), __DIR__.\DIRECTORY_SEPARATOR.'Container0fjlygh');
