<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUigzxyq\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUigzxyq/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUigzxyq.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUigzxyq\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerUigzxyq\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Uigzxyq',
    'container.build_id' => '9d437060',
    'container.build_time' => 1544025317,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerUigzxyq');
